FROM fresh8/golang-base:latest as builder
# copy and setup work dir
COPY . /go/src/github.com/fresh8/dredd/resource-service
WORKDIR /go/src/github.com/fresh8/dredd/resource-service

# Build executable
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /main

ENTRYPOINT ["/main"]
